### ISSUE TITLE
Handling of Update of nested stack template

### ISSUE THREAD

**Issue by AdrieanKhisbe** [concon121/serverless-plugin-nested-stacks#7]
I detected that when you update the nested stack template, without updating the serverless nested stack parameter, the stack is not updated?

I'm I doing something wrong? Or do is this something that is not handled so far?
If so, I can give a hand on the implementation :)

**Comment by concon121** [comment]
I believe this is due to a defect in the creation of the S3 key when uploading the nested stack templates.  Because the nested template definition does not change, cloudformation doesn't bother reading the file and so doesn't detect any change.

As far as I remember, sls creates a uuid for each deployment, so the artifacts for each deployment are kept in separate "folders" in S3.  Adding this uuid into the key for the nested templates would be the ideal solution.

I'll have a deeper dive into this later in the week.

**Comment by concon121** [comment]
Found [here](https://github.com/serverless/serverless/commit/b5da4d09ed920827e311a35f1f1858fa5c8f19a9#diff-a68a56a1e4c2a9161433ca7742f7946a) that the AWS provider sets an artifactDirectoryName variable which contains said timestamp.  I've converted to using this in a branch, just want to test the deploy functionality still works before I merge.

Thinking about adding in custom S3 paths for nested templates and a stand alone deploy e.g sls nested-templates:deploy.  Not sure how that world work yet though!

**Comment by AdrieanKhisbe** [comment]
Okey Dokey. I can review the PR if you want.

> just want to test the deploy functionality still works before I merge.
Maybe we could wait after #6 basic test are set up

**Comment by AdrieanKhisbe** [comment]
Hello @concon121 ,
Any update on this?
This is getting kind of critical for us at @Coorpacademy. I'm here if you need a hand.
=)

**Comment by concon121** [comment]
Hey @AdrieanKhisbe, sorry i've been busy with other things recently.  I believe I pushed a fix for this which is present in the most recent release at version 0.1.1.  Please can you confirm if updating to this version resolves your issue?

**Comment by AdrieanKhisbe** [comment]
And it worked!
Thanks a lot @concon121  😃 
I think we can close the issue. (unless you want to cover it with test first)

**Comment by concon121** [comment]
Glad to hear, i'll shut this down 😄
